# Generated by Django 6.1 on 2026-08-08 15:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0002_alter_document_fichier_alter_utilisateur_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='version',
            field=models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(1.0)]),
        ),
    ]
