# Generated by Django 5.0.12 on 2026-09-11 22:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0007_seed_default_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagechat',
            options={'ordering': ['date_envoi'], 'verbose_name': 'Message chat', 'verbose_name_plural': 'Messages chat'},
        ),
        migrations.AlterField(
            model_name='categorie',
            name='service_associe',
            field=models.CharField(blank=True, help_text='Service principalement concerné par cette catégorie.', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_title', models.CharField(blank=True, default='New chat', help_text="Titre professionnel généré par l'IA pour cette conversation.", max_length=80)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Session chat',
                'verbose_name_plural': 'Sessions chat',
                'ordering': ['-date_modification'],
            },
        ),
        migrations.AddField(
            model_name='messagechat',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='procedures.chatsession'),
        ),
    ]
